name: EmberAeonic
favicon: null
layout_spectrum: 1
typography_spectrum: 0.45712
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0c0000'
    - '#fefe03'
    - '#fe8d01'
    - '#fefefd'
    - '#c14e01'
  brandStrength: 0.6875
  lightness: 0.4375
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
